"""SQLModel models - unified ORM and Pydantic schemas."""
from datetime import datetime
from typing import Optional
from sqlmodel import SQLModel, Field


class TaskBase(SQLModel):
    """
    Base task fields shared across all task variants.

    This class contains the core business fields that are common
    to creating, updating, and reading tasks.
    """
    title: str = Field(
        min_length=1,
        max_length=200,
        description="Task title",
        index=True,
    )
    description: Optional[str] = Field(
        default=None,
        description="Detailed task description"
    )
    completed: bool = Field(
        default=False,
        description="Task completion status"
    )


class Task(TaskBase, table=True):
    """
    Database table model for tasks.

    This model is used by SQLAlchemy to create the database table.
    table=True indicates this is a database table.

    Inherits from TaskBase: title, description, completed
    Adds: id, created_at, updated_at
    """
    __tablename__ = "tasks"

    id: Optional[int] = Field(
        default=None,
        primary_key=True,
        description="Unique task identifier"
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when task was created"
    )
    updated_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when task was last updated"
    )


class TaskCreate(TaskBase):
    """
    Schema for creating tasks (POST /tasks/).

    Inherits from TaskBase: title, description, completed
    Does NOT include: id, created_at, updated_at (auto-generated by database)

    Example:
        {
            "title": "Buy groceries",
            "description": "Milk, eggs, bread",
            "completed": false
        }
    """
    pass


class TaskRead(TaskBase):
    """
    Schema for reading tasks (GET responses).

    Includes all fields: base fields + id + timestamps

    Example:
        {
            "id": 1,
            "title": "Buy groceries",
            "description": "Milk, eggs, bread",
            "completed": false,
            "created_at": "2024-01-15T10:30:00",
            "updated_at": null
        }
    """
    id: int
    created_at: datetime
    updated_at: Optional[datetime]


class TaskUpdate(SQLModel):
    """
    Schema for updating tasks (PATCH /tasks/{id}).

    All fields are optional to support partial updates.
    Only fields provided in the request will be updated.

    Example (partial update):
        {
            "completed": true
        }

    Example (full update):
        {
            "title": "Buy groceries - URGENT",
            "description": "Milk, eggs, bread, coffee",
            "completed": true
        }
    """
    title: Optional[str] = Field(
        default=None,
        min_length=1,
        max_length=200,
        description="Task title"
    )
    description: Optional[str] = Field(
        default=None,
        description="Detailed task description"
    )
    completed: Optional[bool] = Field(
        default=None,
        description="Task completion status"
    )
